![](img/37_cheat.png)

##### <u>Декораторы</u>

In [2]:
def standart_decorator(func):
    def local_func(*args, **kwargs):
        print(f"Работает стандартный декоратор")
        value = func(*args, **kwargs)
        return value
    return local_func

@standart_decorator
def hello():
    print("Hello!")

hello()

Работает стандартный декоратор
Hello!


In [3]:
def argument_decorator(a, b, c):
    def actual_decorator(func):        
        def wrapper(*args, **kwargs):
            print(f"Работает декоратор с аргументами {a}, {b}, {c}")
            value = func(*args, **kwargs)
            return value
        return wrapper
    return actual_decorator

@argument_decorator(a=1, b=2, c=3)
def hello():
    print("Hello!")

hello()

Работает декоратор с аргументами 1, 2, 3
Hello!


##### <u>Библиотека: Кватернионы</u>

In [1]:
import numpy as np
import quaternion

###### Поиск по библиотеке

In [ ]:
# import numpy as np
# s0 = dir(np)

In [ ]:
# import quaternion
# s = dir(quaternion.np)
# for i in s0:
#     s.remove(i)
# s

###### Инициализация

In [3]:
for q in [np.quaternion(1, 0, 0, 0),
          np.quaternion(1, 2, 3, 4),
          np.quaternion(5, 0, 0),
          np.quaternion(5),
          np.quaternion()]:
    print(f"q = {q}")

q = np.quaternion(1, 2, 3, 4)

q = quaternion(1, 0, 0, 0)
q = quaternion(1, 2, 3, 4)
q = quaternion(0, 5, 0, 0)
q = quaternion(5, 0, 0, 0)
q = quaternion(0, 0, 0, 0)


In [4]:
a = np.array([0, 0, 0.5])

q1 = quaternion.from_vector_part(a)
q2 = quaternion.from_euler_angles(a)

q3 = np.quaternion(np.sqrt(1 - np.linalg.norm(a)**2), *a)

print(f"Кватернион из вектора: {q1}")
print(f"Кватернион единичный из вектора: {q3}")
print(f"Кватернион из углов Эйлера: {q2}")

Кватернион из вектора: quaternion(0, 0, 0, 0.5)
Кватернион единичный из вектора: quaternion(0.866025403784439, 0, 0, 0.5)
Кватернион из углов Эйлера: quaternion(0.968912421710645, 0, 0, 0.247403959254523)


###### Преобразования типов

In [66]:
a = quaternion.as_float_array(q)
b = quaternion.np.array(q)
c = quaternion.np.asarray(q)
d = q.components

print(f"Как numpy-массив: {a}")
print(type(a))
print(f"Как numpy-массив: {b}")
print(type(b))
print(f"Как numpy-массив: {c}")
print(type(c))
print(f"Как numpy-массив: {d}")
print(type(d))

Как numpy-массив: [1. 2. 3. 4.]
<class 'numpy.ndarray'>
Как numpy-массив: quaternion(1, 2, 3, 4)
<class 'numpy.ndarray'>
Как numpy-массив: quaternion(1, 2, 3, 4)
<class 'numpy.ndarray'>
Как numpy-массив: [1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [132]:
a = np.array([4, 5, 6, 7])

anw1 = np.append(a, q)
anw2 = np.append(a, q.components)

print(f"Плохой пример: {anw1}")
print(f"Хороший пример: {anw2}")

Плохой пример: [quaternion(4, 0, 0, 0) quaternion(5, 0, 0, 0) quaternion(6, 0, 0, 0)
 quaternion(7, 0, 0, 0) quaternion(1, 2, 3, 4)]
Хороший пример: [4. 5. 6. 7. 1. 2. 3. 4.]


###### Преобразования математические

In [101]:
a = q.real
b = q.vec
w = q.w
x = q.x
y = q.y
z = q.z

print(f"Скалярная часть: {a}")
print(type(a))
print(f"Векторная часть: {b}")
print(type(b))
print(f"Составлющие: {w} {x} {y} {z}")
print(type(w), type(x), type(y), type(z))

Скалярная часть: 1.0
<class 'float'>
Векторная часть: [2. 3. 4.]
<class 'numpy.ndarray'>
Составлющие: 1.0 2.0 3.0 4.0
<class 'float'> <class 'float'> <class 'float'> <class 'float'>


In [103]:
a = quaternion.np.normalized(q)
b = q.normalized()

print(f"Нормированный кватернион: {a} | {b}")
print(type(a), type(b))

Нормированный кватернион: quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221) | quaternion(0.182574185835055, 0.365148371670111, 0.547722557505166, 0.730296743340221)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'>


In [99]:
a = quaternion.np.abs(q)
b = quaternion.np.absolute(q)
d = q.abs()

c = quaternion.np.norm(q)

print(f"Модуль: {a} | {b} | {d}")
print(type(a), type(b), type(d), '\n')

print(f"Норма: {c} (√c = {np.sqrt(c)})")
print(type(c))

Модуль: 5.477225575051661 | 5.477225575051661 | 5.477225575051661
<class 'numpy.float64'> <class 'numpy.float64'> <class 'float'> 

Норма: 30.0 (√c = 5.477225575051661)
<class 'numpy.float64'>


In [27]:
a = quaternion.np.angle_of_rotor(q)
b = q.angle()

print(f"Угол поворота: {a} | {b}")
print(type(a), type(b))

Угол поворота: 4.389231563842282 | 4.389231563842282
<class 'numpy.float64'> <class 'float'>


In [96]:
a = q.conj()
b = q.conjugate()

с = q.inverse()
d = q.reciprocal()

print(f"Сопряженный: {a} | {b}")
print(type(a), type(b), '\n')

print(f"Обратный: {с} | {d}")
print(type(с), type(d))

Сопряженный: quaternion(1, -2, -3, -4) | quaternion(1, -2, -3, -4)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'> 

Обратный: quaternion(0.0333333333333333, -0.0666666666666667, -0.1, -0.133333333333333) | quaternion(0.0333333333333333, -0.0666666666666667, -0.1, -0.133333333333333)
<class 'quaternion.quaternion'> <class 'quaternion.quaternion'>


In [5]:
A = quaternion.as_rotation_matrix(q)
B = quaternion.as_rotation_matrix(q.normalized())

print(f"Матрица поворота из кватерниона A: \n{A}")
print(f"Матрица поворота из кватерниона B: \n{B}")

Матрица поворота из кватерниона A: 
[[-0.66666667  0.13333333  0.73333333]
 [ 0.66666667 -0.33333333  0.66666667]
 [ 0.33333333  0.93333333  0.13333333]]
Матрица поворота из кватерниона B: 
[[-0.66666667  0.13333333  0.73333333]
 [ 0.66666667 -0.33333333  0.66666667]
 [ 0.33333333  0.93333333  0.13333333]]


In [29]:
from scipy.spatial.transform import Rotation as R
A = [[0, -1, 0],
     [1, 0, 0],
     [0, 0, 1]]
q = np.quaternion(*np.roll(R.from_matrix(A).as_quat(), 1))  # roll because [x, y, z, w]
print(f"Кватернион из матрицы поворота A: \n{q}")
print(f"Матрица поворота из кватерниона: \n{quaternion.as_rotation_matrix(q)}")

Кватернион из матрицы поворота A: 
quaternion(0.707106781186547, 0, 0, 0.707106781186547)
Матрица поворота из кватерниона: 
[[ 2.22044605e-16 -1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


##### <u>Аспекты математики в проге</u>

###### Собственные числа

In [1]:
import numpy as np

a = np.array([[0, 1],
              [-1, 0]])

_, v, _ = np.linalg.svd(a)
print(f"Сингулярные числа: {v}")

w, v = np.linalg.eig(a)
print(f"Собственные числа: {w}")

Сингулярные числа: [1. 1.]
Собственные числа: [0.+1.j 0.-1.j]


##### <u>Аспекты проги в проге</u>

###### Быстродействие

`clip`: своё лучше для обычных чисел

In [2]:
import numpy as np
import time

n = int(1e6)

# Моя функция
def clip(a: float, bot: float, top: float) -> float:
    if a < bot:
        return bot
    if a > top:
        return top
    return a

t0 = time.time()
for _ in range(n):
    tmp = clip(-1, 0, 2)
print(f"my-clip: {time.time() - t0} секунд")

t0 = time.time()
for _ in range(n):
    tmp = np.clip(-1, 0, 2)
print(f"np.clip: {time.time() - t0} секунд")

my-clip: 0.11680936813354492 секунд
np.clip: 3.2440905570983887 секунд
